setwd("xtree")
library(Rcpp)
library(devtools)
library(xtree)
load_all()
df = read.csv("../../../data/bh.data", header = FALSE)
# types = convertColTypes(df)
# categ_encodings = convertCategEncodings(df)
# convertData(df, nrow(df), ncol(df), 0, types, categ_encodings)
params = c("lol")

# xtree(df, 5, types, categ_encodings, params)
loadModule("xtree", TRUE)
tree = xtree(df, 0, params)
library(microbenchmark)
microbenchmark(tree$grow())
tree$print()
