# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

xtree <- function(r_data, target_index, coltypes, categ_encodings, params) {
    invisible(.Call(`_xtree_xtree`, r_data, target_index, coltypes, categ_encodings, params))
}

